language: elixir
elixir: 1.9.0

before_script:
  - mix format --check-formatted
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)

